#!/bin/env bash
# Check if less than 4 parameters are passed


if [ "$#" -lt 4 ]; then
  echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
  # Transfer the file using scp with strict host key checking disabled
  scp -o StrictHostKeyChecking=no -i "$4" "$1" "$3@$2:~"
fi
