#!/usr/bin/env bash
#Configures the installed NGINX to:
#+    Listen on port 80.
#+    Return a page containing "Hello World" when queried
#+     at the root with a curl GET request.
# Configures /redirect_me as a "301 Moved Permanently".
# Includes a custom 404 page containing "Ceci n'est pas une page".


apt-get update
apt-get install -y nginx


# Configure Nginx to show customized html content
echo "Hello World!" > /var/www/html/index.nginx-debian.html

# Configure Nginx to redirect /redirect_me to another page
sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' /etc/nginx/sites-available/default

# Configure Nginx to have a custom 404 page
echo "Ceci n'est pas une page" > /usr/share/nginx/html/404.html
sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' /etc/nginx/sites-available/default

# Restart Nginx to apply changes
service nginx restart
