#!/usr/bin/env bash
# Configures an Nginx server to include a custom response header with the server's hostname

# Ensure correct usage
error="Usage: $0 HOSTNAME"
if [[ $# -lt 1 ]]; then
  echo "$error"
  exit 1
fi

# Set hostname
HOSTNAME=$1
sudo hostnamectl set-hostname "$HOSTNAME"

# Update and install Nginx
sudo apt-get update
sudo apt-get -y install nginx

# Configure Nginx to serve custom HTML content
echo "Hello World!" | sudo tee /var/www/html/index.nginx-debian.html

# Configure Nginx to redirect /redirect_me to another page
sudo sed -i '/listen 80 default_server;/a rewrite ^/redirect_me https://www.youtube.com/watch?v=QH2-TGUlwu4 permanent;' \
/etc/nginx/sites-available/default

# Configure Nginx to have a custom 404 page
echo "Ceci n'est pas une page" | sudo tee /usr/share/nginx/html/404.html
sudo sed -i '/server_name _;/a error_page 404 /404.html;\nlocation = /404.html {\nroot /usr/share/nginx/html;\ninternal;\n}' \
/etc/nginx/sites-available/default

# Configure Nginx to add custom header with server's hostname
sudo sed -i '/server_name _;/a add_header X-Served-By $hostname;' \
/etc/nginx/sites-available/default

# Restart Nginx to apply changes
sudo service nginx restart

echo "Nginx configured with custom header X-Served-By on hostname $(hostname)."
