#!/usr/bin/env bash
# Kills the "4-to_infinity_and_beyond" process.

# Use 'pgrep' to find the PID of the "4-to_infinity_and_beyond" process and then 'kill' it.

PID=$(pgrep -f 4-to_infinity_and_beyond)
kill "$PID"
