#!/usr/bin/env bash
# Use a while loop to display time for 12 hours

# Initialize the hour variable
hour=0

while [ $hour -le 12 ]; do
  echo "Hour: $hour"
  minute=1
  while [ $minute -le 59 ]; do
    echo $minute
    ((minute++))
  done
  ((hour++))
done
