#!/usr/bin/env bash
# Get the directory contents (excluding hidden files)

# Get the directory contents and store in cd_content
cd_content=$(ls)

# Use a for loop to process the directory contents
for file in $cd_content; do
    if [[ $file != .* ]]; then
	filename=$(echo "$file" | cut -d'-' -f2-)

	echo "$filename"
    fi
done
