#!/usr/bin/env bash
# Install and configure Nginx to run as 'nginx' user and listen on port 8080

apt-get update
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

service nginx restart
