#!/usr/bin/env bash
# Install and configure Nginx to run as 'nginx' user and listen on port 8080

apt-get update
apt-get install -y nginx
sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
echo 'listen 8080;' >> /etc/nginx/sites-available/default
systemctl restart nginx
