#!/usr/bin/env bash
# Install and configure Nginx to run as 'nginx' user and listen on port 8080

sed -i 's/user www-data;/user nginx;/g' /etc/nginx/nginx.conf
sed -i 's/listen 80;/listen 8080;/g' /etc/nginx/sites-available/default

chmod 644 /etc/nginx/nginx.conf
pkill apache2
sudo -u nginx service nginx start
