#!/usr/bin/env bash

# Define the parameters for the RSA key
key_name="school"
key_bits="4096"
passphrase="betty"

# Generate the RSA key pair
ssh-keygen -t rsa -b "$key_bits" -f "$key_name" -N "$passphrase"
